/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "outline-variant": "#494454",
              "on-background": "#dae2fd",
              "surface-container-low": "#131b2e",
              "inverse-primary": "#6d3bd7",
              "secondary-container": "#03b5d3",
              "on-primary-container": "#340080",
              "inverse-on-surface": "#283044",
              "error-container": "#93000a",
              "surface-container-high": "#222a3d",
              "on-tertiary-fixed": "#36003e",
              "on-tertiary-fixed-variant": "#7c008e",
              "secondary-fixed-dim": "#4cd7f6",
              "inverse-surface": "#dae2fd",
              "on-primary-fixed": "#23005c",
              "surface-container-highest": "#2d3449",
              "surface-dim": "#0b1326",
              "on-secondary-fixed-variant": "#004e5c",
              "on-error-container": "#ffdad6",
              "outline": "#958ea0",
              "secondary-fixed": "#acedff",
              "on-secondary-fixed": "#001f26",
              "on-secondary": "#003640",
              "primary-fixed-dim": "#d0bcff",
              "on-primary-fixed-variant": "#5516be",
              "error": "#ffb4ab",
              "surface-container": "#171f33",
              "surface-tint": "#d0bcff",
              "on-primary": "#3c0091",
              "on-tertiary-container": "#4d0059",
              "surface-variant": "#2d3449",
              "tertiary-container": "#e14ef6",
              "secondary": "#4cd7f6",
              "on-secondary-container": "#00424e",
              "primary": "#d0bcff",
              "primary-fixed": "#e9ddff",
              "tertiary-fixed-dim": "#fbabff",
              "surface-bright": "#31394d",
              "surface-container-lowest": "#060e20",
              "on-surface": "#dae2fd",
              "tertiary-fixed": "#ffd6fd",
              "tertiary": "#fbabff",
              "on-tertiary": "#580065",
              "surface": "#0b1326",
              "background": "#0b1326",
              "on-surface-variant": "#cbc3d7",
              "on-error": "#690005",
              "primary-container": "#a078ff"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "unit": "8px",
              "container-max": "1280px",
              "margin-desktop": "48px",
              "gutter": "24px",
              "margin-mobile": "16px"
      },
      "fontFamily": {
              "display-lg-mobile": ["Outfit"],
              "display-lg": ["Outfit"],
              "mono-label": ["Space Mono"],
              "headline-sm": ["Outfit"],
              "label-md": ["Inter"],
              "body-lg": ["Inter"],
              "headline-md": ["Outfit"],
              "body-md": ["Inter"]
      },
      "fontSize": {
              "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "mono-label": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
              "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-md": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
